name: Playground workflow

on: push

jobs:
  playground-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          [[ $(ip -4 addr show dev eth0 | grep "inet") =~ ([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})/[0-9]{1,2} ]]
          ipaddr="${BASH_REMATCH[1]}"
          echo ${ipaddr}
